coverage:
  parsers:
    javascript:
      enable_partials: yes
  status:
    project:
      default:
        target: "80%"
        threshold: "1%"
    patch:
      enabled: false
comment: false
ignore:
  - "src/utilities/testing/**"
  - "**/__tests__/**"
